### ISSUE TITLE
Node throwing error 'unexpected identifier' on volumio 2.861 for config.js (modules.exports)

### ISSUE THREAD

**Issue by LeisureLadi** [richiewebgate/volumio-mqtt#13]
After installation of volumio-mqtt on version volumio 2.861 the configuration file 'config.js' is not processed correctly, when trying the script with:

volumio@volumio:/opt/node/volumio-mqtt$ sudo node server.js

This is the error:
module.exports = {
^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/node/volumio-mqtt/server.js:2:14)

Can you provide some help?

Best regards

**Comment by richiewebgate** [comment]
Hi!

this looks to me like there is an illegal/unrecognized character in config.js.
the module.exports = { line looks ok so far, can you post a little more of that config.js file?

did you edit it with nano directly on linux, or have you transferred it from a windows system? maybe a CRLF issue?

PS: please don't start node with "sudo".

cheers!
